name: deploy-manifests

on:
  push: # so it won't run on PR close or something like that, not necessary
    branches:
      - main
    paths:
      - 'infra/**'
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: digitalocean/action-doctl@v2 # let DO installs doctl
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - run: doctl kubernetes cluster kubeconfig save ticketing
      - run: kubectl apply -f infra/k8s # apply all config files to cluster
