name: deploy-ticketing-client

on:
  push: # so it won't run on PR close or something like that, not necessary
    branches:
      - main
    paths:
      - 'ticketing-client/**'
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd ticketing-client && docker build -t viettran1010/ticketing-client .
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push viettran1010/ticketing-client
      - uses: digitalocean/action-doctl@v2 # let DO installs doctl
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - run: doctl kubernetes cluster kubeconfig save ticketing
      - run: kubectl rollout restart deployment ticketing-client-depl
      
